/*
 * This source file was generated by the Gradle 'init' task
 */
package org.app;

import org.junit.Test;

import static org.junit.Assert.*;

import org.Main;

public class AppTest {
    @Test public void appHasAGreeting() {
        Main classUnderTest = new Main();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
