package org;
/*
 * This source file was generated by the Gradle 'init' task
 */


import java.net.InetSocketAddress;

import org.handlers.HealthCheckHandler;
import org.handlers.EndpointHandler;
import org.http.Endpoint;

import com.sun.net.httpserver.HttpHandler;
import com.sun.net.httpserver.HttpServer;

public class Main {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Endpoint[] endpoints = new Endpoint[] {
            new Endpoint("/health", new EndpointHandler()),
        };
        
        try {
            HttpServer server = HttpServer.create(new InetSocketAddress(8080), 0);

            for (Endpoint endpoint : endpoints) {
                server.createContext(endpoint.getPath(), endpoint.getHandler().getHandler());
            }
            
            server.start();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }    
}
